hystrix:
  image: bluemeric/2pnik_0:1465899579317752271.hthv78j2
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: bluemeric/1pnik_0:1465899579317752271.hthv78j2
  ports:
   - "8761:8761"
configserver:
  image: bluemeric/3pnik_0:1465899579317752271.hthv78j2
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: bluemeric/4pnik_0:1465899579317752271.hthv78j2
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - user
   - movie
   - recommendation
user:
  image: bluemeric/7pnik_0:1465899579317752271.hthv78j2
  links:
   - discovery
   - configserver
movie:
  image: bluemeric/6pnik_0:1465899579317752271.hthv78j2
  links:
   - discovery
   - configserver
recommendation:
  image: bluemeric/8pnik_0:1465899579317752271.hthv78j2
  links:
   - discovery
   - configserver
moviesui:
  image: bluemeric/5pnik_0:1465899579317752271.hthv78j2
  ports:
     - "9006:9006"
  links:
   - discovery
   - configserver
